[package]
name = "kdbx-fortress-vault-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
keepass = { git = "https://github.com/HyperCriSiS/keepass-rs", rev = "521a49707a4dd2a5cb0ddae92d39448ca79771b6", default-features = false }

[dev-dependencies]
base64 = "=0.22.1"
keepass = { git = "https://github.com/HyperCriSiS/keepass-rs", rev = "521a49707a4dd2a5cb0ddae92d39448ca79771b6", default-features = false, features = ["save_kdbx4"] }
