[package]
name = "kdbx-fortress-vault-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
keepass = { git = "https://github.com/HyperCriSiS/keepass-rs", rev = "2c70c4b56f124ee19c5c338ef33615d97eba39ba", default-features = false }

[dev-dependencies]
base64 = "=0.22.1"
keepass = { git = "https://github.com/HyperCriSiS/keepass-rs", rev = "2c70c4b56f124ee19c5c338ef33615d97eba39ba", default-features = false, features = ["save_kdbx4"] }
