[package]
name = "kdbx-fortress-vault-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
zeroize = "=1.9.0"
keepass = { git = "https://github.com/HyperCriSiS/keepass-rs", rev = "bdf81aa77cafdf6651c0909d4dbcceb2a15ad227", default-features = false }

[dev-dependencies]
base64 = "=0.22.1"
keepass = { git = "https://github.com/HyperCriSiS/keepass-rs", rev = "bdf81aa77cafdf6651c0909d4dbcceb2a15ad227", default-features = false, features = ["save_kdbx4", "test_fixture_tools"] }
