[workspace]
members = ["vault-core"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.97.1"
license = "AGPL-3.0-only"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
print_stdout = "deny"
print_stderr = "deny"
